added several new samples and articles
openwhisk/awesome-openwhisk pull request #16
Opened 2017-02-22 16:23 UTC by romankhar

also made some changes to the sub-titles of sections

2017-02-22 16:25 UTC, rabbah commented on README.md
> +- [Official OpenWhisk Tutorial](https://github.com/openwhisk/openwhisk-tutorial) - Interactive tutorials for learning how to use OpenWhisk.
Tutorial and later tutorials. Should both be plural?

2017-02-22 16:26 UTC, rabbah commented on README.md
> +- [Logistics Wizard](https://www.ibm.com/blogs/bluemix/2017/02/microservices-multi-compute-approach-using-cloud-foundry-openwhisk/) is an enterprise-grade sample application which leverages OpenWhisk
application -> applications?

2017-02-22 16:26 UTC, rabbah commented on README.md
> +- [Web Actions](https://medium.com/openwhisk/web-actions-serverless-web-apps-with-openwhisk-f21db459f9ba) - This sample shows hot to use OpenWhisk to build a complete Web App.
hot -> how.

2017-02-22 16:27 UTC, rabbah commented on README.md
> +- [Dark vision](https://github.com/IBM-Bluemix/openwhisk-darkvisionapp) - application that shows how to use OpenWhisk, Cloudant, Watson Visual Recognition, Object Storage to process video frames, tag
capitalize "a" in "application".

2017-02-22 16:27 UTC, rabbah commented on README.md
> +- [Dark vision](https://github.com/IBM-Bluemix/openwhisk-darkvisionapp) - application that shows how to use OpenWhisk, Cloudant, Watson Visual Recognition, Object Storage to process video frames, tag
same below for "d" in "demonstrates"

2017-02-22 16:33 UTC, romankhar commented on README.md
> +- [Official OpenWhisk Tutorial](https://github.com/openwhisk/openwhisk-tutorial) - Interactive tutorials for learning how to use OpenWhisk.
fixed it (it was already there :-) )

2017-02-22 16:34 UTC, romankhar commented on README.md
> +- [Logistics Wizard](https://www.ibm.com/blogs/bluemix/2017/02/microservices-multi-compute-approach-using-cloud-foundry-openwhisk/) is an enterprise-grade sample application which leverages OpenWhisk
changed to "12-factor style applications"

2017-02-22 16:34 UTC, romankhar commented on README.md
> +- [Web Actions](https://medium.com/openwhisk/web-actions-serverless-web-apps-with-openwhisk-f21db459f9ba) - This sample shows hot to use OpenWhisk to build a complete Web App.
done

2017-02-22 16:35 UTC, romankhar commented on README.md
> +- [Dark vision](https://github.com/IBM-Bluemix/openwhisk-darkvisionapp) - application that shows how to use OpenWhisk, Cloudant, Watson Visual Recognition, Object Storage to process video frames, tag
done

2017-02-22 16:36 UTC, romankhar commented
all fixed and commited

2017-02-22 16:49 UTC, jthomas requested changes
I want to keep the "applications" section with links to Github repositories. 
Can you move the links that point to Medium blog posts to the articles section?

2017-02-22 16:50 UTC, jthomas commented
@mrutkows can you give me write access to this repo? I've filed my CLA.

2017-02-22 17:06 UTC, romankhar commented
every one of those Medium articles has associated Repo with a complete sample - do we need to list it twice - once under Articles and once under Samples? I would rather have it under Samples since most people wont look at the list of articles when there are looking for a sample

2017-02-22 17:28 UTC, csantanapr requested changes
I would like to see Sample Applications sections pointing to github repos. in addition a link to the companion blog/article should be added.
Each application bullet ideally would have two links the primary one to the repo, and secondary (optional) to the companion blog/article.

Also we should check if the repo itself should also have a link to the companion article.

In the Article section, should only be links to blog/article that don't have associated repo. and only a link to the article.

2017-02-22 21:07 UTC, romankhar commented
I replaced links under samples with links to GitHub and moved those without GitHub to "articles". Please take a look at this and feel free to edit directly - as soon as we are all done editing it, I will copy&paste into my fork and refresh the PR: https://docs.google.com/document/d/1PIYg1sUDV8wimnm5H9imVJ7ZPXEGLzD3LhW4qKzkQ_Y/edit?usp=sharing

2017-02-23 09:26 UTC, jthomas commented
LGTM.

2017-02-23 09:36 UTC, csantanapr approved these changes

2017-02-23 09:36 UTC, merged