Add Lastversion.info article link
openwhisk/awesome-openwhisk pull request #20
Opened 2017-02-28 16:48 UTC by shaftoe

2017-02-28 17:19 UTC, jthomas requested changes

2017-02-28 17:19 UTC, jthomas commented on README.md
> +- [Lastversion.info](http://alexanderfortin.tumblr.com/post/157820499911/lastversion-a-go-serverless-proof-of-concept) - An HTTP service to fetch latest stable version of OpenSource projects, written
The formatting is broken here.

2017-02-28 21:40 UTC, shaftoe commented on README.md
> +- [Lastversion.info](http://alexanderfortin.tumblr.com/post/157820499911/lastversion-a-go-serverless-proof-of-concept) - An HTTP service to fetch latest stable version of OpenSource projects, written
I just changed the leading "a" to capital to conform with the rest of the document

2017-03-01 10:03 UTC, jthomas approved these changes

2017-03-01 10:03 UTC, merged